ci: sh pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,11 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# Navigacija do backend direktorija i izvođenje lintinga
-cd backend && npm run lint
-if [ $? -ne 0 ]; then
-  echo "Backend linting failed"
-  exit 1
-fi
+if git diff --cached --quiet -- neox-api/; then
+  exit 0
+else
+  cd neox-api && npm run check:lint-all
+ if [ $? -ne 0 ]; then
+   echo "Backend linting failed"
+   exit 1
+ fi
